# Inspired by:
# https://michaelcurrin.github.io/code-cookbook/recipes/ci-cd/github-actions/workflows/node/upgrade-packages.html
name: Upgrade dependencies

on:
  schedule:
    # https://crontab.guru/#0_8_*_*_1
    - cron: "0 8 * * 1"
  workflow_dispatch:
  workflow_call:

jobs:
  upgrade-packages:
    name: Upgrade npm packages

    runs-on: ubuntu-latest

    steps:
      - name: ğŸ›ï¸ Checkout
        uses: actions/checkout@v4

      - name: âš™ï¸ Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "npm"

      - name: â¬‡ï¸ Install dependencies
        run: npm ci

      - name: ğŸ” Check for outdated packages
        id: check
        run: |
          # Log execution steps
          # set -x

          # Stop everything if there is any error
          # set -e

          # Get the list of npm package in dependencies that have more recent versions
          OUTDATED=$(npm outdated || true)

          if [[ -z "$OUTDATED" ]]; then
            # There is no package with more recent versions
            echo 'Nothing to upgrade' >> "${GITHUB_STEP_SUMMARY}"

            # Set a variable to know that next steps should NOT be run
            echo "upgradable=false" >> "${GITHUB_OUTPUT}"
          else
            # There are packages with more recent versions

            # Get the header of the packages table
            HEADER=$(echo "$OUTDATED" | grep "Package")

            # Get the list of packages that will really be upgraded, with compatible semver
            COMPATIBLE=$(echo "$OUTDATED" | awk '$2!=$3' | grep -v "Package" || true)
            if [[ -z "$COMPATIBLE" ]]; then
              # There is no compatible upgrade
              COMPATIBLE_COUNT=0
            else
              # Count how many compatible upgrades are available
              COMPATIBLE_COUNT=$(($(echo "$COMPATIBLE" | wc -l) + 0))
            fi

            # Get the list of packages that have recent versions not compatible with semver
            NOT_COMPATIBLE=$(echo "$OUTDATED" | awk '$2==$3' || true)
            if [[ -z "$NOT_COMPATIBLE" ]]; then
              # There is no not compatible upgrade
              NOT_COMPATIBLE_COUNT=0
            else
              # Count how many not compatible upgrades are available
              NOT_COMPATIBLE_COUNT=$(($(echo "$NOT_COMPATIBLE" | wc -l) + 0))
            fi

            if [[ $COMPATIBLE_COUNT -gt 0 ]]; then
              # There are compatible upgrades, let's list them in the Action summary
              {
                echo "${COMPATIBLE_COUNT} package(s) will be upgraded:"
                echo '```'
                echo "${HEADER}"
                echo "${COMPATIBLE}"
                echo '```'
              } >> "${GITHUB_STEP_SUMMARY}"

              # Keep track of this list for the Pull Request body
              delimiter="$(openssl rand -hex 8)"
              {
                echo "upgrades_list<<${delimiter}"
                echo "${COMPATIBLE_COUNT} package(s) will be upgraded:"
                echo '```'
                echo "${HEADER}"
                echo "${COMPATIBLE}"
                echo '```'
                echo "${delimiter}"
              } >> "${GITHUB_OUTPUT}"

              # Set a variable to know that next steps should be run
              echo "upgradable=true" >> "${GITHUB_OUTPUT}"
            else
              echo 'Nothing to upgrade' >> "${GITHUB_STEP_SUMMARY}"

              # Set a variable to know that next steps should NOT be run
              echo "upgradable=false" >> "${GITHUB_OUTPUT}"
            fi

            if [[ $NOT_COMPATIBLE_COUNT -gt 0 ]]; then
              # Also show the list of not compatible upgrades in the Action summary
              {
                echo ''
                echo "${NOT_COMPATIBLE_COUNT} not compatible upgrade(s):"
                echo '```'
                echo "${HEADER}"
                echo "${NOT_COMPATIBLE}"
                echo '```'
              } >> "${GITHUB_STEP_SUMMARY}"
            fi
          fi

      - name: â« Upgrade packages
        id: upgrade
        if: steps.check.outputs.upgradable == 'true'
        run: |
          npm update --save

      - name: ğŸ§ Lint
        if: steps.check.outputs.upgradable == 'true'
        run: npm run lint --if-present

      - name: ğŸš¨ Test
        if: steps.check.outputs.upgradable == 'true'
        run: npm run test --if-present

      - name: ğŸ—ï¸ Build
        if: steps.check.outputs.upgradable == 'true'
        run: npm run build --if-present

      - name: ğŸ”€ Commit and create PR
        if: steps.check.outputs.upgradable == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.PAT }}
          title: "build(deps): upgrade NPM packages"
          body: |
            # Updating dependencies

            ${{ steps.check.outputs.upgrades_list }}

          branch: "upgrade-dependencies"
          delete-branch: true
          commit-message: "build(deps): upgrade NPM packages"
          labels: |
            type: dependencies ğŸ”—
            automerge ğŸ¤
